### ISSUE TITLE
2017.02.13 통합테스트 이슈

### ISSUE THREAD

**Issue by skaqud** [blackmaz/saltstack_test#10]
1. 이슈

- ssh접속을 위한 known_host 사전 등록해야 하는 문제가 있음

- hostname 사전에 수정해야 하는 문제 - 지금 이름이 분간이 안됨, 어느시점에 누가 수정할지...
hostname, internalip, eip 관계를 알 수 있어야 함 --> K에게 전달

- script 수정부분
script에서 salt설치하는 부분 제거, password빼고, sudo True넣었음.  --> K에게 전달

2. 지켜야 할 부분들

- state두는 위치를 고민, 같은 ozr에서도 db, was각각의 위치

- 주석 달기 - 한글로

- 각자 AWS상에서 통합테스트 해 보기

**Comment by blackmaz** [comment]
호스트네임 설정 관련한 아마존 매뉴얼 확인해본 결과 생성시에 세팅하는 기능은 없고 OS 상에서 변경하고 서버를 reboot 하라고 가이드 되어 있음
salt-minion 설정하는 절차에서 다음 둘중 한가지 방식으로 적용
1) hostname 변경
2) 변경없이 salt minion의 이름을 가지고 식별

**Comment by blackmaz** [comment]
ssh known_host 등록여부 확인 메시지
- salt-master의 ssh 설정에 다음과 같이 추가하면, host key 등록여부를 확인하지 않고 자동으로 등록함

# vi /etc/ssh/ssh_config 
ForwardX11Trusted yes <- 요거 밑에다
StrictHostKeyChecking no <- 요거 추가
