### ISSUE TITLE
2017.2.18 통합테스트 이슈

### ISSUE THREAD

**Issue by blackmaz** [blackmaz/saltstack_test#13]
ozr/tomcat.sls : rename-tomcat-dir: --> 디렉토리 무브 하다가 에러가 남, apache/init.sls도 동일 디렉토리를 web root로 잡고 설정을 해야 해서 만들고 있는데, 이미 만들어져 있으니 무브를 못하고 에러가 남 --> 복사로 변경하면 안될까?

ozr/deploy.sls
에러없이 돌아가는데 tomcat 부팅중에 익셉션이 남.-->데이터 접속관련 설정 확인
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'qzDS': java.sql.SQLException: Connections could not be acquired from the underlying database! [See nested exception: java.sql.SQLException: Connections could not be acquired from the underlying database!]

https://www.ozr.kr/ 접속시 index.jsp로 연결이 안됨--> apache 설정 추가 필요

**Comment by skaqud** [comment]
rename-tomcat-dir 요건 기본적으로 apache 설정파일을 풀면 경로가 같이 들어있어서 버전명인데, 그걸 현재경로와 맞춰 놓은 거구요, ( cd /www/nest;mv apache-tomcat-7.0.75 tomcat7 ) 요 부분입니다. 그냥 기존 디렉토리 남기고 cp -rp 로 바꿀까요?

deploy.sls -> 확인해보니 DB root 비번 설정부터 에러가 나서, 이후가 줄줄이 꼬이는 것 같습니다. ubuntu에서 확인했고, mysql state로 설치 후 ozr.mysql_db_import 를 실행해봤습니다. 혹시 제가 잘못 실행한 부분 있으면 말씀해주시구요

**Comment by blackmaz** [comment]
ozr/tomcat.sls : rename-tomcat-dir: file.copy로 변경
mysql/init.sls : mysql_root_password : unless 구문 제거 --> 패스워드 설정시 워닝이 나오는데 정상적으로 작동은 하는것 같음

--> 변경해서 커밋함..
