### ISSUE TITLE
2017.2.19 테스트 이슈

### ISSUE THREAD

**Issue by blackmaz** [blackmaz/saltstack_test#14]
1. mysql/init.sls : mysql_root_passwd --> 따로 떨어져서 돌아갈 때는 문제 없는데, 자동으로 돌리면 알수 없는 에러가 남..ㅠㅠ

2. apache/vhost.sls : ssl을 사용할 때 (use_ssl) vhost 설정이 *:443 이면 접속시 에러 발생 IP:443으로 바꿔야 함 --> grains 이용해서 자기 자신의 IP 받아오도록 수정 해야 함 (SSL_ERROR_RX_RECORD_TOO_LONG)

3. AP-DB 분리 됨에 따라 app 내부에 DB 접속정보 변경 필요
/www/nest/tomcat7/webapps/WEB-INF/classes/config/spring/context-datasource.xml 
/www/nest/tomcat7/webapps/WEB-INF/classes/config/properties/quartz.properties
: localhost --> db 서버 ip또는 hostname, dns 등 (grains 이용해서 DB 서버 IP를 어디엔가 세팅해놓고 불러와야 함)

4. 아마존 Security Group에 외부 접속 port를 열어야 할 경우는 어떻게 연계 할지--> with 김길한...ozr은 443을 기본적으로 사용하는데 열려있지 않음

5. 어플리케이션 --> 개발계를 말아와서 초기 화면이 개편중 화면임--> 운영계 소스로 다시한번 말아서 배포해 봐야 함...

**Comment by skaqud** [comment]
3. 우선 pillar에서 별도로 입력하도록 했습니다. db의 ip를 가져오기가 힘들 것 같습니다.

5. 운영계의 webapps는 1GB이상이라 파일 전체를 올리기 힘들 것 같은데요, 발라낼 수 있는지 확인해 보겠습니다.

**Comment by skaqud** [comment]
5. 운영계 파일을 같은 이름으로 다시 올려놨습니다. data디렉토리 크기가 큰데, 그 안에서  project와 smarteditor 관련 디렉토리가 900메가 이상이라 해당 디렉토리만 제외하고 올렸습니다.

**Comment by blackmaz** [comment]
5. 개편중 화면 나오는건 index.jsp로 보내는 설정이 빠져 있어서 그랬음...

DirectoryIndex index.html index.htm index.jsp <== 추가
