### ISSUE TITLE
Mysql 한글 설정

### ISSUE THREAD

**Issue by blackmaz** [blackmaz/saltstack_test#23]
Mysql 설치 후 한글 insert 시 ??로 입력됩니다. 
@Lyune 기본 캐릭터 셋을 utf-8로 지정하도록 설정 하는 SLS를 추가해 주세요.

**Comment by Lyune** [comment]
CentOS의 경우 character_set_server=utf8
Ubuntu의 경우 
collation-server = utf8_unicode_ci
character-set-server = utf8
skip-character-set-client-kandshake
추가했습니다.
