### ISSUE TITLE
ui와 연결시 사용할 정보 정의

### ISSUE THREAD

**Issue by blackmaz** [blackmaz/saltstack_test#3]
ui에서 받아와야할 정보를 xml로 정의해야 함

**Comment by blackmaz** [comment]
일단 초안 잡아봄

Application:
  - name: pandamall
  - categories:
    - shoping mall
    - E-commerce
  - urls:
    - www.pandamll.com
    - pandamall.com
  - devepement langauge: php
  - softwares:
    - nginx:
      - software-name: nginx
      - software-type: webserver
      - version: latst
      - cfg-root: /etc/nginx #
      - site-cfg: conf.d     #
      - use-logical-server: webserver  
      - default:    # server_ip:80
        - doc-root: /var/www
        - log-root: /var/nginx
      - virtual-hosts:
        - www.pandamll.com:
          - vhost-type: named    # dns를 통해서 접근
          - listen-ip: *
          - listen-port: 80
          - doc-root: /var/www/pandamall
          - log-root: /var/nginx/pandamall
          - back-end-services: 
            - php:
              - pattern: ~*.php/*  # 백엔드 요청으로 넘길때 판단하는 패턴, mime type
              - type: php-fpm
              - location: 'http://127.0.0.1:9000'
              - use-php-pool: pandamall.conf
            - mysql:
              - use-mysql-scheam: pandamall
        - www.pandamll.com:
          - vhost-type: port     # ip:port를 통해서 접근
          - listen-ip: *
          - listen-port: 8080
          - doc-root: /var/www/pandamall
          - log-root: /var/nginx/pandamall
          - back-end-service: php
    - php:
      - software-name: php
      - software-type: middleware
      - version: 7.0
      - cfg-root: /etc/php/{{version}}
      - site-cfg: pool.d
      - use-logical-server: webserver
      - pools:
        - www.conf:
          - listen-type: socket
          - listener-uri: /run/php/php7.0-fpm.sock
        - pandamall.conf:
          - listen-type: net
          - listener-uri: 127.0.0.1:9000
    - mysql:
      - software-name: mysql
      - software-type: database
      - version: latest
      - cfg-root: /etc/mysql/mysql.conf.d
      - site-cfg: ???
      - use-logical-server: dbserver
      - schemas:
        - pandamall:
          - user: pandamall
          - database: pandamalldb
          - access-logical-sever: webserver
  - logical-servers:
    - webservers:
      - web1
      - web2
    - dbservers:
      - db1
  - pyshical-servers:
    - web1:
      - ext-ip: 203.1.1.10
      - int-ip: 192.168.0.5
    - web2:
      - ext-ip: 203.1.1.11
      - int-ip: 192.168.0.6
    - db1:
      - ext-ip: 203.1.1.12
      - int-ip: 192.168.0.7

**Comment by skaqud** [comment]
대략적으로 한 번 적어봤습니다. 전 SW부분만, 나머지는 조수석님 따라 가도 될 것 같습니다.

고민할 부분
- 너무 많은 설정도 좋지 않다.. 사용자 입장에서.. 서비스를 구성하는 필수만 있어야 하지 않을까
- 비슷한 용어별 조정 필요

apache
    version
    tarball
    insthome
    home
    configfile
        apache2.conf
            listen-address
            listen-port
        ajp_config
        proxy_config

sun-java
    version
    tarball
    insthome
    home

tomcat
    version
    tarball
    insthome
    home
    configfile
        bin/catalina.sh
            java_opts
        conf/server.xml
            connector
                ports
                maxThreads
    deploy
        application_name
            home
            config

mariadb
    version
    tarball
    insthome
    home
    configfile
        my.cnf
    database
        name
        user
        password
        script

**Comment by Lyune** [comment]
[소프트웨어]
  - name
  - 배치위치 [logical servers]
  - sw별 설정정보

[logical server]
  - name
  - 배치위치 [physical servers]

[Physical server]
  - name
  - ROLE : 각 소프트웨어의 역할( ex. Db master / db slave ... )
  - Physical server 별 설정정보

Physical server 의 role 에 따라 설정
개별 설정정보는 정리해 주신대로 하면 될듯합니다.

**Comment by blackmaz** [comment]
<application>
	<name>www.pandamall.com</name>
	<desc>.......</desc>
	<tarball>srcdir/filename.tar</tarball>
	<deploy>/app/pandamall</deploy>
</application>

<software>
	<id>nginx</id>
	<name>nginx</name>
	<version>latest</version>
	<relation>
		<software>php</software>
		<logical-server>ls-web01</logical-server>
	</relation>
	<configuration>
		<home>/etc/nginx</home>
		<loghome>로그파일 기본 위치</loghome>	
		<conffile name="nginx.conf">
			<worker_processes>auto</worker_processes>
			<error_log>{{ loghome }}/error.log</error_log>
			<pid>/run/nginx.pid</pid>
			<events>
				<worker_connections>1024</worker_connections>
			</events>
			<http>
				<log_format></log_format>
				<access_log></access_log>
				<keepalive_timeout>65</keepalive_timeout>
				<default_type>application/octet-stream</default_type>
				<server>
					<listen>8080 default_Server</listen>
					<server_name></server_name>
					<root>/usr/share/nginx/html</root>
					<index>index.html</index>
					<location name="~ \.php$" >
						<fastcgi_pass>127,0.0.1:9000;</fastcgi_pass>
					</location>
				</server>
			</http>
		</conffile>
	</configuration>
</sofrware>

<software>
	<id>php</id>
	<name>php</name>
	<version>7.0</version>
	<relation>
		<software>nginx</software>
		<software>mysql</software>
		<logical-server>ls-web01</logical-server>
	</relation>
	<configuration>
		<cfg-root>/etc/php</cfg-root>
		<site-cfg>pool.d</site-cfg>
		<pools>
			<pool name="www.conf">
				<listen-type>socket</listen-type>
				<listener-uri>/run/php/php7,0-fpm.sock</listener-uri>
			</pool>
			
		</pools>
	</configuration>
</software>

<software>
	<id>mysql</id>
	<name>mysql</name>
	<version>latest</version>
	<logical-server>ls-db01</logical-server>
	<configuration>
		<home>/etc/mysql</home>
		<configfile name="my.cnf" role="master">
			<server_id>1</server_id>
		</configfile>
		<configfile name="my.cnf" role="slave">
			<server_id>2</server_id>
		</configfile>
	</configuration>
</software>

<logical-server>
	<id>ls-web01</id>
	<desc>webserver</desc>
</logical-server>

<logical-server>
	<id>ls-db01</id>
	<desc>db server</desc>
</logical-server>

<physical-server>
	<id>web01</id>
	<ip>
		<ext-ip>x.x.x.x</ext-ip>
		<int-ip>y.y.y.y</int-ip>
	</ip>
	<logical-server>ls-web01</logical-server>
	<role>default</role>
</physical-server>

<physical-server>
	<id>web02</id>
	<ip>
		<ext-ip>x.x.x.x</ext-ip>
		<int-ip>y.y.y.y</int-ip>
	</ip>
	<logical-server>ls-web01</logical-server>
	<role>default</role>
</physical-server>

<physical-server>
	<id>db-master</id>
	<ip>
		<ext-ip>x.x.x.x</ext-ip>
		<int-ip>y.y.y.y</int-ip>
	</ip>
	<logical-server>ls-db01</logical-server>
	<role>master</role>
</physical-server>

<physical-server>
	<id>db-slave</id>
	<ip>
		<ext-ip>x.x.x.x</ext-ip>
		<int-ip>y.y.y.y</int-ip>
	</ip>
	<logical-server>ls-db01</logical-server>
	<role>slave</role>
</physical-server>
