### ISSUE TITLE
Sprint1 Test issues

### ISSUE THREAD

**Issue by skaqud** [blackmaz/saltstack_test#32]
Sprint1 Test issues

**Comment by skaqud** [comment]
- itsSvr.py 통해서 실행시 input_file='' 인자 없으면 오류나는 것 같습니다. input_file, company_cd, system_cd들을 채워넣고 다음과 같이 실행하고 있는데, 방법이 맞나요?? 

    python itsSvr.py -n mysql
    python itsSvr.py -n tomcat

- 원인은 잘 모르겠는데, site_sp1 pillar에서는 오류가 나고 site_petc는 오류가 안납니다.(전체는 아니고 tomcat만 들어가도록 편집해도 나네요..) 오류가 나는 지점은, lookupHostBySwName 요기인것 같습니다. 예상 가시는 부분이 있을까요?

**Comment by blackmaz** [comment]
- 지난번 변경시에 sw명을 인수로 받도록 요청을 받아서 고치면서 input_file 인자는 삭제했습니다. 명령 실행방법은 ./itsSvr.py -n tomcat -c sp1 -s petclinic 로 해보세요..
- 신규로 pillar 파일을 추가하면 /srv/pillar/top.sls에도 추가해 줘야 합니다.

**Comment by skaqud** [comment]
6.13 협의내용을 기반으로 작업해야 할 내용은

화면에서  libcloud+salt 관련 내용들을 xml형태로 저장할 예정, libcloud쪽에서는 해당 XML을 sls로 만들어 salt에서 실행할 수 있도록 할 예정입니다. xml, sls를 전달해 드려 샘플을 실행해서 생성할 수 있도록 하면 될 것 같은데, 기존 sls가(yaml) xml로 바꾸려고 보니 다음과 같은 문제가 있습니다. 

- xml포맷에 맞게 변경(공백 제거, /와 같은 context path제거), xml 포맷 기준으로 attribute를 변경하고 동일한 이름으로 sls도 변경
- sls변경에 대해 테스트(python script, salt script변경 필요)

**Comment by skaqud** [comment]
- site_sp1.xml
  - 화면에서 저장해 줄 파일, libcloud에 application쪽 태그하위에 들어갈 예정입니다.(sls의 software부분만 들어가 있습니다.)
  - xml로 변환하다 보니 태그 명에 공백->_로 대체, /등의 path명은 root로 변경했습니다. 태그화 하다보니 의미가 맞지 않는 부분(80,도메인명을 태그로 만들어야 하는 부분등)이 있습니다. sls에서 실행되는지를 확인하고 해당 부분은 변경하는 게 맞을 것 같습니다.
  - 너무 복잡할 경우 libcloud쪽에서 만들기 힘들지 않을까 싶네요, 효율적으로 단순화 할 수 있는 방법이 없을까요?
- site_sp1.sls
  - 위의 포맷에 맞게 attribute 명 변경하였습니다. python script, salt script테스트 필요합니다.
  - nginx, tomcat의 context 부분은 아직 그대로 놔두었습니다. 테스트 해보면서 xml과 sls를 같이 변경해야 할 것 같습니다.

**Comment by skaqud** [comment]
혹시 시간 되시는 분 ubuntu에서 site_replica 쪽 테스트 부탁드립니다. 정상적으로 실행이 안되고 있는 것 같네요.. 테스트는 ubuntu 14.04에서 해봤습니다. 그동안 변경된 부분은 sls안의 attribute 명 등이 공백일 경우 다 _로 연결하도록 바뀌었고, python script도 맞게 바뀐 정도입니다.

**Comment by blackmaz** [comment]
site_replica 확인중이고요, mysql state도 같이 손보고 있습니다.
토요일까지 테스트 완료해서 푸시하겠습니다.

**Comment by skaqud** [comment]
별도로 메일이 가겠지만, 금일 저희쪽 해당하는 협의내용입니다.

salt 할일
- aliyun에서 salt script 실행 테스트(생성 step에 맞춰)
- operator에서 실행해야 하는 부분 정리해서 전달
- node를 삭제하지 않아도 salt를 다시 테스트 할 수 있도록 삭제하는 salt state 만들기(삭제?,cleanup state 작성)

github 등 공통 형상을 쓰는 문제
- private 계정 존재 확인 후 실행여부 확인 -> 이후 소스를 올릴 수 있는 방법 공지
- 아직은 협업 요건이 많지 않아 기존 repository를 사용하되(남아있다면) 구체적인 논의는 sprint1 끝난 후 다시 하기로 하였습니다.
  -> 우선은 public repository들 주소를 정리해서 공유하겠습니다.

itsbox(web)
- https://github.com/blackmaz/itsbox
itsbox_operator
- https://github.com/cool8519/itsbox_d_operator
itsbox_salt
- https://github.com/blackmaz/saltstack_test

**Comment by blackmaz** [comment]
site_replica는 테스트 완료해서 푸시 했으나 한가지 문제가 남아 있음
mysql slave node 셋팅할때 master node의 정보를 참고해서 세팅하는데
salt에서 동시에 두 노드에 대해 명령을 던지면, 경우에 따라서 성공하기도/실패하기고 하는것 같음.
(master가 셋업되어 있으면 성공하고 그렇지 않음 실패...)

**Comment by skaqud** [comment]
sprint1에서 uninstall하는 state를 별도로 만들어, 테스트시에 node를 삭제하지 않고 다시 테스트 해 볼 수 있게 하려고 하는데, 실행은 어떻게 하는 게 좋을까요? python script를 통해 실행할 때는 init으로만 들어가게 되는데, 좋은 의견 있으시면 말씀해주세용

**Comment by skaqud** [comment]
operator쪽과 얘기할 step들입니다. 문제 되는 부분이 있으면 알려주세요

### 테스트 절차
1. node생성 - master,git repository는 설치 되어있음(operator)
2. salt ssh를 이용해 minion 설치(/etc/salt/roster) - 연결까지 완료
- python itsRoster.py -c sp1 -s petclinic
- python itsInit.py -p ubuntu -c sp1 -s petclinic
3. 어플리케이션 설치
nginx
- python itsSvr.py -n nginx -c sp1 -s petclinic
tomcat
- python itsSvr.py -n tomcat -c sp1 -s petclinic
mysql
- python itsSvr.py -n mysql -c sp1 -s petclinic
4. 어플리케이션 삭제(-u)
- python itsSvr.py -u nginx -c sp1 -s petclinic

**Comment by blackmaz** [comment]
삭제기능을 만들다 보니 옵션을 변경했습니다. 
4. 어플리케이션 삭제
python itsSvr.py -n nginx -c sp1 -s petclinic -t uninstall

**Comment by skaqud** [comment]
별도로 메일이 가겠지만, 금일 테스트 시 이슈내용입니다.

- 금일 이슈
  - tomcat을 두 번이상 다른 조건으로 설치해야 할 때(예를 들어 다른 버전으로?) software하단에 정의하는 방법(같은 SW를 다른 속성으로 설치해야 할 경우)
  - 설치할 어플리케이션의 목록을 알 수 있는 방법? - 현재는 operator쪽에서 설치명령을 어떤 내용을 몇 번 실행할지 알 수 없음 

금일은 주로 웹 화면 - 커뮤니케이터 - operator 쪽만 테스트 했습니다. 중간중간 operator - salt쪽을 위해 aliyun에서 생성하는 테스트, 위의 테스트 절차도 공유했습니다.
저는 우선 앞쪽에서 생성되는 걸 가정하고 개발서버 - aliyun의 생성된 node간에 테스트 절차대로 되는지 확인해 보겠습니다.

**Comment by blackmaz** [comment]
* tomcat을 두 번이상 다른 조건으로 설치해야 할 때(예를 들어 다른 버전으로?) software하단에 정의하는 방법(같은 SW를 다른 속성으로 설치해야 할 경우)
  * Why? application을 여러 개 deploy하는거랑 차이는 뭘까?
  * 레거시 환경에서는 필요할것 같은데 클라우드 환경에서도 그렇게 할까? (m2.micro도 커서 was를 여러개 올리려는 것이라면 차라리 Docker를 지원하는게 좋을거 같은 느낌이 듭니다.)
  * VM --> (Docker엔진 설치 --> Docker 컨테이너 생성)~~> 여기를 saltstack으로 구현하는게 어떨까?
* 설치할 어플리케이션의 목록을 알 수 있는 방법? - 현재는 operator쪽에서 설치명령을 어떤 내용을 몇 번 실행할지 알 수 없음
  * pillar/site_~~~.sls에 software 부분을 1번씩 실행해 주면 되는데 몇번 실행한다는 것의 의미를 모르겠네요? 
  * 서버 대수가 여러대인걸 대응하려고 한다면, pillar의 site_~~.sls 구조를 다시한번 설명해주는게 맞을거 같음

**Comment by skaqud** [comment]
개발서버에서 테스트 중인데, 실행시 다음과 같은 문제가 있습니다. 혹시 제가 잘못한 부분이 있으면 말씀해주시기 바랍니다. 시간날때마자 계속 해 보겠습니다. 
- roster파일 생성 : python itsRoster.py -c sp1 -s petclinic 명령 실행시 파일이 생성 안됨. 확인해보니 적어도 하나 이상의 minion이 있어야 pillar정보를 가져올 수 있음. 자신을 minion설정하기 위해 minion으로 추가하고 실행해 보았으나 파일이 생기지 않음.
- minion 설치 : python itsInit.py -p ubuntu -c sp1 -s petclinic 실행시 물리서버 정보를 못 가져옵니다. 역시 pillar에서 물리서버 정보를 못가져오 는 것 같아서, pillar내용을 확인해보니 site_sp1.sls에 정의된 pillar들이 올라오지 않네요. 다른것들은 있는 것 같아 혹시 올라갈 수 있는 크기가 제한이 있나 해서, top.sls에 사용할 sls만 정의해봤으나 상태는 동일한 것 같습니다.

다음은 추가 고민사항(금일 권0님하고 얘기한 부분입니다.설명이 충분하지 않을 수 있고, 제가 까먹은 부분이 있을 수 있습니다)
- roster파일 생성 부분은 operator쪽에서 생성해도 될 것 같다고 함, sudo는 첫글자를 대문자로 해도 되는지?, sudo 여부는 화면에서 받는 게 맞을지?
- Logical Server정의부분이 operator쪽에 없음, software말고 다른 이름으로 추가 필요.
- xml 태그 보완 : 값이 태그가 되는 경우(sample의 petclinic 태그 같은 경우)에 파싱에 문제가 있으므로, name, value등을 적절히 사용하여 xml의미에 맞게 변경 필요

**Comment by blackmaz** [comment]
* salt master에서 pillar 읽어오는 부분은 salt-call api를 사용했기 때문에 salt-call을 설치해 줘야 하는데, 내가 빼먹고 안해놓은듯.... 개발서버에 salt user로 세팅해놓은거 같기도 한데... 다시 확인해볼께
* site_sp1.sls에 오타가 있거나 yaml 형식에 맞지 않는 부분은 없는지 확인해볼것.

**Comment by blackmaz** [comment]
개발서버 접속할때 salt / salt 로 접속하고
salt-master의 root 디렉토리가 /home/salt/srv/~~ 입니다.
/srv 사용하지 마세요.
어떤 유저로 어떻게 테스트 했는지 간단하게 적어주세요.

**Comment by skaqud** [comment]
금일 테스트시 오류인 듯한 부분입니다.(개발서버에서 확인)
1. Roster파일 생성시 파일이 있으면(/etc/salt/roster) 아무 반응이 없고 생성도 안됨, 지우고 다시 실행하면 됩니다.
- python itsRoster.py -c sp9 -s petclinic
---> 이건 할때마다 덮어쓰는 게 맞을까요?
2. minion 설치시 -p 하위에 비번에 !,@등 특문이 들어가면 정상적으로 동작이 안됩니다. -> aliyun은 비번 생성시 넣으라고 강제합니다. 비번 빼고 돌리면 정상적으로 minion 설치됩니다.
- python itsInit.py -p mypassword!23(이러면 오류) -c sp9 -s petclinic
3. 한대에 대해서 web,was만 설치해보려고 테스트하는데, 다음과 같이 오류가 나네요.
- python itsSvr.py -n nginx -c sp9 -s petclinic
AttributeError: 'list' object has no attribute 'items'

**Comment by blackmaz** [comment]
1. Roster 파일 생성
* 이거 만들때 동일한 ID로 요청이 또 들어오면, 그냥 업데이트 해버릴까 아니면 에러를 낼까 고민하다가 최종으로 정리를 못해놓고 임시로 처리해 놓은것입니다. 
* 내 생각엔 다음과 같이 처리하도록 코드를 좀더 보완해야 할 것 같아요
  * 동일한 ID로 다시 생성하면 아무것도 안하고 나가 버리게 되어 있음, 에러처리 추가
  * 동일한 ID에 대한 변경처리는 update 메소드를 추가로 정의

2. 패스워드의 특수문자
* 특수문자 처리는 특별할게 없어보이는데 문자열을 어떻게 저장하는지 확인해보겠습니다.

3. 오류 관련
* 에러가 발생한 다음에 로그 처리하는 부분에서 제대로 처리를 못하고 있는것 같은데
* pillar에 뭐가 빠져서 나는 에러인듯 함...
* 테스트 케이스를 push해 놓으면 돌려보겠습니다.

**Comment by blackmaz** [comment]
1. 옵션을 추가해서 -t add 하면 변경된거 무시하고 신규만 넣은걸로 -t change는 변경된것 업데이트도 하는 걸로 수정해서 올렸습니다. 최종 결과 출력도 넣었으니 참고..
2,3 관련해서 itsInit.py에 로그를 추가해서 푸시했으니까 돌려보고 어디서 에러 나는지 피드백 부탁해요.

**Comment by blackmaz** [comment]
3. 한대에 대해서 web,was만 설치해보려고 테스트하는데, 다음과 같이 오류가 나네요.
python itsSvr.py -n nginx -c sp9 -s petclinic
AttributeError: 'list' object has no attribute 'items'
* sls 랜더링 에러가 나는경우에 dict가 아니라 list로 로그가 내려와서 나는 에러입니다.
타입 체크 해서 list인 경우에 별도 처리하는 로직을 넣었습니다.

**Comment by skaqud** [comment]
몇가지 공유&여쭤봅니다.

1.deprecation warning 발생
/usr/lib/python2.7/dist-packages/salt/client/__init__.py:704: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.
--> 아직은 별 문제는 되지 않을 것 같습니다만, 나중에는 차후를 생각해야 할 것 같습니다.

2.uninstall 시 다음과 같은 에러 발생
python itsSvr.py -n tomcat -c s33 -s petclinic -t uninstall
Rendering SLS 'base:tomcat.uninstall' failed: Jinja variable 'str object' has no attribute 'install'
-> 요건 좀 더 찾아보겠습니다.

3.
위의 문제를 찾기 위해 다음과 같이 테스트로 실행했더니 - salt-call pillar.get base:tomcat.jdk
아래와 같은 에러가 나는 것 같습니다.
[ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Minion failed to authenticate with the master, has the minion key been accepted?
salt '*' cmd.run 'xxxxx~~' 와 같이 실행하면 명령은 나오는 걸로 봐서 연결된 것 같긴 한데요..

**Comment by blackmaz** [comment]
* 2번 uninstall 시 에러는 pillar에 inatall 이란 변수를 못찾아서 나는건데. -c s33은 어떤 site sls에 정의된건지 확인좀 해주세요.

**Comment by skaqud** [comment]
s33은 테스트로 만들었던 거구요. 올라와있는 p33에서도 동일하게 발생하네요..

['de2oall_test']['state.apply'][['tomcat.uninstall', 'pillar={"company": "p33", "system": "petclinic"}']]
Rendering SLS 'base:tomcat.uninstall' failed: Jinja variable 'str object' has no attribute 'install'

그리고 pillar에는 있는데 아래와 같이 못찾는 경우가 있습니다. salt client에서 메세지를 뱉는 것 같습니다...

['de2oall_test']['state.apply'][['tomcat', 'pillar={"company": "p33", "system": "petclinic"}']]
Rendering SLS 'base:tomcat' failed: Jinja variable 'dict object' has no attribute 'jdk'

**Comment by skaqud** [comment]
원인은 명확한데 아직 해결책은 못 찾았습니다.

일부 sls에서 pillar에서 값들을 못찾아오는 경우가 발생합니다. company와 system등 runtime pillar를 못가져와서 그런 것 같구요.
되는 곳은 되는 걸로봐서 뭔가 잘못한 것 같긴 한데.... 더 찾아보겠습니다...ㅠ.ㅠ

**Comment by blackmaz** [comment]
일단... site_p33.sls는tomcat에 install이라는 변수가 정의되지 않아서 렌더링 하면서 에러가 나는거네..
언인스톨 테스트 하려면 인스톨도 정확하게 되도록 변수 정의하고 돌려보는게 좋을거 같음..
'''
salt@DE2ODEV:~/srv/pillar$ salt-call --local pillar.get p33:petclinic:software
local:
    ----------
    tomcat:
        ----------
        deploy_server:
            was
        jdk:
            openjdk
'''
