### ISSUE TITLE
Redirection을 위한 virtual host 설정

### ISSUE THREAD

**Issue by blackmaz** [blackmaz/saltstack_test#5]
오지랖 apache 설정에 예전에 사용했었을 듯 해 보이는 도메인 이름을 새로운 사이트로 리디렉션 하는 설정이 제법 많이 있음... 중소 기업일 수록 도메인 변경이 많을테고... 한명이라도 아쉬우니 유지하려는 경향이 높을듯...

웹서버 단에 여러개의 도메인을 한쪽으로 전달해주는 설정 추가 필요함

**Comment by blackmaz** [comment]
apache/vhost.sls 
 - redirect: 구현 완료
 - mod-jk:  미구현
 - mod-proxy: 미구현
 - php: 미구현

**Comment by skaqud** [comment]
반영완료
