### ISSUE TITLE
웹서버 ssl 설정(nginx, apache)

### ISSUE THREAD

**Issue by blackmaz** [blackmaz/saltstack_test#6]
많이 쓰는 설정인데 고려하지 못했음.
추가할 필요 있음

인증서 관련 부분 확인도 필요하고..

**Comment by blackmaz** [comment]
apache/openssl.sls
 - self-signed certi. 형태로 구현
 - 외부 인증서 설치 구현예정
이슈: ubuntu apache2에서 vhost에서 ssl 사용시 에러 발생 --> IP기반 vhost로 해야 에러가 안남(추가 확인 필요)

**Comment by skaqud** [comment]
반영완료
